# Generated by Django 2.0.3 on 2020-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('small', models.IntegerField(blank=True, null=True)),
                ('large', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
