# Generated by Django 2.0.3 on 2020-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('Toppings', 'Toppings'), ('Subs', 'Subs'), ('Pasta', 'Pasta'), ('Salads', 'Salads'), ('Dinner Platters', 'Dinner Platters')], max_length=64),
        ),
    ]
