# Generated by Django 2.1.5 on 2020-03-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200328_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('topping1', models.CharField(blank=True, max_length=64, null=True)),
                ('topping2', models.CharField(blank=True, max_length=64, null=True)),
                ('topping3', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
