# Generated by Django 2.1.5 on 2020-03-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='topping4',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='toppings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
